apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agents.openagentspec.org
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: openagentspec.org
  # list of versions supported by this CustomResourceDefinition
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: agents
    # singular name to be used as an alias on the CLI and for display
    singular: agent
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Agent
    listKind: AgentList
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                description:
                  type: string
                intent:
                  type: string
                owner:
                  type: string
                capabilities:
                  type: object
                  additionalProperties:
                    type: object
                    properties:
                      collect_results:
                        type: boolean
                      user_identity:
                        type: boolean
                      static_identity:
                        type: string
                        nullable: true
                      input_restriction:
                        type: object
                        nullable: true
                        properties:
                          require_review:
                            type: string
                            nullable: true
                          assertion:
                            type: string
                            nullable: true
                      output_restriction:
                        type: object
                        nullable: true
                        properties:
                          require_review:
                            type: string
                            nullable: true
                          assertion:
                            type: string
                            nullable: true
                guardrails:
                  type: object
                  nullable: true
                  properties:
                    input:
                      type: object
                      nullable: true
                      properties:
                        tool_name:
                          type: string
                        assertion:
                          type: string
                    output:
                      type: object
                      nullable: true
                      properties:
                        tool_name:
                          type: string
                        assertion:
                          type: string
                exposes:
                  type: object
                  nullable: true
                  additionalProperties:
                    type: string  # Assuming OAGENT_SELECTION is a string or identifier
                lifespan:
                  type: object
                  nullable: true
                  properties:
                    retain_memory:
                      type: boolean
                    short_circuit:
                      type: integer
